steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cal-agent:latest', '.']
  use_buildkit: true

images: ['gcr.io/$PROJECT_ID/cal-agent:latest']
options:
  logging: CLOUD_LOGGING_ONLY
